language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
addons:
  hosts:
    - munin.test

before_script:
  - sudo apt-get update
  - sudo apt-get install munin-node telnet
  - echo "allow ^::1$" | sudo tee -a /etc/munin/munin-node.conf
  - sudo service munin-node restart
  - cat /etc/munin/munin-node.conf
  - cat /etc/hosts
  - composer self-update
  - composer install

script: "phpunit --configuration ./tests/travis-phpunit.xml"